### ISSUE TITLE
Injector configuration

### ISSUE THREAD

**Issue by ackoujens** [ackoujens/tunerstudio-valor-740-super-turbo#20]
# Injectors

![image](https://user-images.githubusercontent.com/4503038/109417929-fc19ce80-79c5-11eb-987d-bb3b0d881bb1.png)

## Description
Type: 0 280 155 968
Brand: Bosch
Spray pattern: Twin cone
Resistance: 12 ohm
Connector: EV1 Jetronic style
_AKA "Skinny greens"_

Finding technical data which is accurate is difficult though and may require me to test them myselves. CC/MIN change all of the time, along with different fuel pressures. It's a blind move inputting this info in your TS project. A self made testing setup is really a must on the todo list!

_(Data from selling page @ bosch-motorsport-shop.com.au)_
BOSCH NUMBER | LBS/HR | CC/MIN | GRAMS/MIN | PSI | BAR
-- | -- | -- | -- | -- | --
0-280-155-968 | 41 | 453 | 310 | 43.5 | 3

_(Data from tiperformance.com.au - PDF)_
BOSCH NUMBER | LBS/HR | CC/MIN | GRAMS/MIN | PSI | BAR
-- | -- | -- | -- | -- | --
0-280-155-968 | 41 | 453 | 310 | 55.1 | 3.8

-(Data from robietherobot.com fuel injector guide - Less reliable data IMO)-
BOSCH NUMBER | LBS/HR | CC/MIN | GRAMS/MIN | PSI | BAR
-- | -- | -- | -- | -- | --
0-280-155-968 | 44.25 | 465.1 | 334.5 | 55.1 | 3.8
0-280-155-968 | 39.32 | 413.2 | N/A | 43.5 | 3

This is a minor tweak but getting this right may also lead to not tweaking other values on top of it afterwards. More issues happen on default values with big injectors though. Smaller injectors can run perfectly on standerd TS settings.

## Calibration data
Calibration data is not easy to find and probably because every setup is unique and should be tested in the current setup it is in. Already sent out an email to bosch motorsports dep for any technical data they have. But I already suspect this is going to be a wasted effort.

So we should be looking out to make a test setup to have somewhat accurate flow/dead time data.

## Todo
- [x] Define exact injector model
- [ ] Find Injector documentation for flow/dead time/other specs
- [ ] Set Required Fuel
- [ ] Set Injector Dead Time/PWM
- [ ] Test injectors on current setup for flow & dead times

**Comment by ackoujens** [comment]
# Injectors (Old setup)

![image](https://user-images.githubusercontent.com/4503038/101243350-0e0a0f00-3700-11eb-831a-be67996422f7.png)

## Description
Type: 0 280 150 804
Brand: Bosch

_(Unreliable data?)_
BOSCH NUMBER | LBS/HR | CC/MIN | GRAMS | PSI | BAR
-- | -- | -- | -- | -- | --
0-280-150-804 | 32.05 | 336.8 | 242.3 | 43.5 | 3

_(This has been refered to as B230FK injectors, more reliable)_
![image](https://user-images.githubusercontent.com/4503038/101243509-2169aa00-3701-11eb-8541-96ba35eeb568.png)

This is a minor tweak but getting this right may also lead to not tweaking other values on top of it afterwards. More issues happen on default values with big injectors though. Smaller injectors can run perfectly on standerd TS settings.

![image](https://user-images.githubusercontent.com/4503038/101239421-ae076e80-36e7-11eb-9e6e-961750af81af.png)

## Setup not in use
This set of injectors have been removed for a new set. Check the top post for the latest.
We have no idea how old these are and if they still flow properly. (my best guess is not)
Will keep them to clean these and retest if they are still able to be reused.
