### ISSUE TITLE
Ignition configuration

### ISSUE THREAD

**Issue by ackoujens** [ackoujens/tunerstudio-valor-740-super-turbo#21]
# Ignition

## Description

Coil type: Delphi GN10119 LS2 coil

Ignition setup works fine as is but probably could work better when set to spec. Dwell tends to change on different loads so a battery correction needs to be applied as well for charging/discharging situations.

## Todo
- [x] Find exact coil model
- [x] Find coil configuration specs
- [x] Set base ignition configuration
- [x] Set Dwell Table
- [x] Set Dwell Battery Correction

## Sources
- https://www.jfetech.nl/epages/080402.sf/en_GB/?ObjectPath=/Shops/080402/Products/LS2-Coil%2BConn
- https://goflowforce.com/ls-coil-instructions
