### ISSUE TITLE
Engine warmup time using an EWP

### ISSUE THREAD

**Issue by ackoujens** [ackoujens/tunerstudio-valor-740-super-turbo#27]
# Operating temperature

## Current setup
As the car sits right now, an EWP is installed to replace the functionality of the mechanical pump. Still installed, the mechanical pump still allows for coolant to flow through.

The thermostat is removed from the housing as recommended by Davies Craigs instructions. The EWP controller decides when to run the pump or ramp the pump up/down, looking at it's dedicated temperature sensor.

The pump runs in intervals even when the engine isn't up to temp.
Cooling capacity of the pump might be overkill even when only pulsing. Since the thermostat isn't present, there is always maximum flow possible.

## What is considered normal?
Another car in the fleet has almost the same engine setup though not turbocharged. A comparison is in order to determine what a usual warmup time with a mechanical thermostat should be. Allowing only a minimum of flow through the block while the engine is cold.

## The repair
Should I replace the OEM thermostat in the neck or replace with a drilled plate? Or install the thermostat with drilled holes so the flow only increases when warmed up?

Another thought is to take a look at the EWP controller. An alteration in the settings could resolve this issue as well.

## Todo
- [x] Test B230FK operating temperature time
- [x] Compare test to turbo engine warmup time
- [x] Check on EWP/FB forum
- [x] Reinstall original thermostat (modified for more flow)
- [x] Replace coolant
- [x] Test changes

**Comment by ackoujens** [comment]
![image](https://user-images.githubusercontent.com/4503038/101838479-fa680980-3b40-11eb-98b4-ecbf6d23233d.png)

Testing showed the EWP having too much cooling power on low pulsing mode, making the engine hard to warm up.
Operating temperature will probably be possible when a constriction is applied.
A modified thermostat would do the trick.

**Comment by ackoujens** [comment]
Having a poll out on a Volvo Facebook group and sent an email to Davies Craig to follow up recommendations in their instructions. Maybe explaining why it's sensible to replace the original thermostat.

**Comment by ackoujens** [comment]
Other people on forums also confirming having an issue of too much cooling, solved by installing a thermostat.
https://www.hpacademy.com/forum/general-tuning-discussion/show/pwm-a-electric-water-pump

**Comment by ackoujens** [comment]
From the response of Davies Craig & Facebook I've got 2 main choices:
- Reinstall thermostat (drill 2x 5 mm holes) - gasket/reseal thermostat neck - replace distilled water <-> coolant
- Leave OEM EWP controller out of the loop and rewire EWP to Megasquirt to be controlled there (more control over duty cycle & intervals)

**Comment by ackoujens** [comment]
After making these changes, the temperature curve should be equal or better to a mechanical setup.
Another thought would be to test the exhaust runner temperatures.
If only a few cylinders are firing properly, warmup time will also be longer. 
(check for large differences on each runner side)

Test setup after making all changes:
- [x] Measure new temperature curve over time
- [x] Check exhaust runner temps for consistent operation

**Comment by ackoujens** [comment]
**New Temperature Curve**
Cooling system has been flushed since it was very much contaminated with rust and other gunk.
The coolant was then replaced with a proper product instead of just distilled water.

Along with that, a tested OEM thermostat was reinstalled. This thermostat also has 2 drilled holes of 5 mm each according to Davies Craig recommendations. Cooling system is sealed and has shown no leaks.

After doing some similar tests, the curve has not improved by much but the car has been able to reach operating temperature. (yellow line)

![image](https://user-images.githubusercontent.com/4503038/101993486-6bcbc780-3cbb-11eb-9a57-86f9a81b3a5d.png)


**Exhaust Runner Check**
Temperatures were very different across all exhaust runners so this instigated this exhaust research.
Cylinders 1-2-3 are all around 200 - 240 degrees. The 4th cylinder is only around 100 °C.
But while measuring the temperature of the turbocharger I noticed this was around the same temperature as cylinder 1 to 3.
This explains much because the 4th cylinder is the furthest from the turbo. All other cylinders are basically right next to it.

**Comment by ackoujens** [comment]
Coupled this issue with PR #26 to re-check temperature curve after a perfect idle has been established.
VE/Timing/Idle in general are suspected to be a contributing factor.

So basically we need to mess around with idle VE and timing to achieve a better result.

**Comment by ackoujens** [comment]
Due to increased pressure on the coolant overflow tank, along with the non-impressive results. I've decided to remove the thermostat again. We'll check for operating temperature times later on the road. Having a light load on the engine, light cruising. Like it's supposed to be when driving a car in general.

I'll compare these to the carbureted 740 and a newer model Volvo (S40 T2R) we have.
Since the goal of this project is to bring the 740 more up to spec and above. It would be great to get the quick warmup times of a newer-age car.

- [x] Remove thermostat and reseal
- [x] Rotate EWP CTS sensor to point down for a stealthier look (WYAT)
- [ ] Test Volvo S40 time to operating temperature (normal driving)
- [ ] Test Volvo 740 B230K time to operating temperature (normal driving)
