### ISSUE TITLE
Calibrate all ECU sensors

### ISSUE THREAD

**Issue by ackoujens** [ackoujens/tunerstudio-valor-740-super-turbo#4]
# Calibration of measuring instruments

## Description
One of the most basic steps if done wrong, it might undo a lot of work done to tuning.
Also this can result in you figuring out how to fix certain kind of table, messing with other values.
The ECU wants to know what is going on inside and around the engine to be able to deliver smart calculations and overcome dangerous situations for your engine.

Look for model numbers and the correct documentation before entering custom calibration values!

## Sources
- https://roadsterzoku.wordpress.com/2015/09/07/megasquirt-ecu-part-1-setup-and-calibrations/
- https://bartuneengineering.wordpress.com/guides/megasquirt-ecu-setup/
- https://projectcars.io/build/exocet-30/2019/03/05/overcoming-megasquirt-start-up-and-idle-issues

**Comment by ackoujens** [comment]
# Wideband

## Description
Wideband sensor has a megasquirt preset but can be further calibrated to comply to minor tolerances.
When switching the wideband on, different values pass along to aid in calibration.

Calibration appears to be done during warmup so the sensor doesn't need to be warmed up all the way.

This sensor should be reading max lean with the engine not running.

## Todo
- [x] Research cold or operating temperature check
- [x] Calibrate wideband in TS

## Calibration refinement
Initial values set at 0-5V (10-20 AFR)
Refinement is needed to correct minor errors. (Excel sheet calculator)

![image](https://user-images.githubusercontent.com/4503038/101241885-5f170480-36fa-11eb-81ee-dd83af4abb91.png)

## Resources
Megasquirt calibration procedure:
https://www.14point7.com/blogs/news/16539352-maximizing-accuracy-between-spartan-2-and-megasquirt

Spartan 3 Wideband/controller documentation:
[Spartan_3_ADV_User_Manual_863b29af-76fa-4c51-9a6a-8f20e621840f.pdf](https://github.com/ackoujens/tunerstudio-valor-740-super-turbo/files/5451180/Spartan_3_ADV_User_Manual_863b29af-76fa-4c51-9a6a-8f20e621840f.pdf)

**Comment by ackoujens** [comment]
# MAP Sensor

## Description
MAP sensor will be simple as it is the on board one. 
Which is soldered to the board.

Calibration of the MAP sensor is not needed if you're not having issues.
The sensor should be reading near 100kpa if you're near sea level.

![image](https://user-images.githubusercontent.com/4503038/101242724-8cb07d80-36fb-11eb-84e8-20cca67dba71.png)
_Unaltered kpa at key-on_

There is a standard preset you can pick for sensing and correction:
![image](https://user-images.githubusercontent.com/4503038/97429951-6cc9b500-1918-11eb-874b-c075769a653b.png)

## Todo
- [x] Research other MAP sensor calibrating procedures
- [x] Calibrate MAP sensor

**Comment by ackoujens** [comment]
# CLT Sensor

## Description
Currently, there are 2 different coolant temperature sensors installed in the cooling system.
One is being used by the EWP (Electric Water Pump) and is isolated from the ECU, installed in the upper radiator hose.
Other sensor is installed into the OEM location into the cast iron block.

Should these values read the same temperature? One is installed in a cast iron block, the other in a plastic adapter going through a rubber hose. In cold temperatures cast iron might conduct the ambient cold more than rubber.
This could be negated when running at operating temperature though.

Normally when cold, this sensor should read near ambient temperature.
So go check the weather forecast or better, go get a thermometer!
This should be close to the air temperature as well (IAT).

## Todo
- [x] Find exact sensor model
- [x] Obtain spec sheet with voltage/temperature readout
- [x] Calibrate CTS sensor in TS
- [x] Compare temperature in TS with thermometer ambient temp
- [x] Compare with EWP coolant sensor

## Current State Readings
6-7°C Analogue Thermometer
? °C Digital Thermometer (too slow)
3°C Coolant Temp Sensor (post-radiator)
9°C Air Temp Sensor
4-5°C EWP Coolant Temp Sensor (pre-radiator)

## Resources
### Sensor Model Image (0 280 130 032)
![image](https://user-images.githubusercontent.com/4503038/98361183-5f54af00-202b-11eb-9216-b989d7250939.png)

Coolant temperature sensor documentation:
[bosch sensors_temperature.pdf](https://github.com/ackoujens/tunerstudio-valor-740-super-turbo/files/5451142/bosch.sensors_temperature.pdf)

_Not sure if data is reliable_
[55001_water_temp_sensor_datasheet.pdf](https://github.com/ackoujens/tunerstudio-valor-740-super-turbo/files/5644838/55001_water_temp_sensor_datasheet.pdf)

**Comment by ackoujens** [comment]
# IAT Sensor

## Description
Intake air temperature sensor is ofter the same as a coolant sensor. (few degrees of ambient temperature) Slight alterations to the design are possible.
But in practice, these sensors can be interchangeable. The ECU relies heavily on this value being accurate.

Heatsoak can affect the sensors performance and lead to hard starts if installed in a bad location.

## Todo
- [x] Find exact sensor model
- [x] Obtain spec sheet with voltage/temperature readout
- [x] Calibrate IAT sensor in TS

## Calibration Data
C° | F° | Ohms
-|-|-
8,88889° | 48° | 7000
30,5556° | 87° | 1930
63,3333° | 146° | 560

## Resources
Type: GM sensor
Purchasing source: https://www.jfetech.nl/epages/080402.sf/en_GB/?ObjectPath=/Shops/080402/Products/IATwConn

**Comment by ackoujens** [comment]
# TPS Sensor

## Description
The throttle position sensor is the simplest sensor to calibrate of them all.
Just hold the pedal in, press a button, release and do the same thing.
Currently there is a Volvo 850 TPS installed after doing some alterations to make it fit and adapt.

## Todo
- [x] Calibrate TPS sensor in TS
