### ISSUE TITLE
Setting up CEL settings

### ISSUE THREAD

**Issue by ackoujens** [ackoujens/tunerstudio-valor-740-super-turbo#7]
![image](https://user-images.githubusercontent.com/4503038/99903902-aac3ba00-2cc7-11eb-98f2-6e2dc41bff94.png)
Set up check engine light settings and wire up a light to turn on when CEL state is activated. Need to research which parameters should be put in to be considered bad for the engine. Making the CEL only activate in dire conditions instead of a short jump over tight value.

# Configuration
- Sensor checking: ON
- Light output: ON 
  - needs to be wired to dash cluster CEL light
  - OEM CEL is unused at the moment anyway
  - Configured on **SPK H**
- CEL SolidFlash codes: Flash-codes 
  - read issue type from blinking code
  - static light doesn't tell much until hooking up laptop
- Ignore fluctuations for first: 20s
  - can be tweaked for higher value but should suffice
- Enabled devices
  - MAP sensor
  - MAT sensor
  - CLT sensor
  - TPS sensor
  - Battery voltage
  - EGO1 (AFR on 02 sensor)
  - Sync-Loss check (Crank position sensor)
- Minimum/maximum ADC
  - Can be tweaked lower/higher if false CEL's are noticed
  - Back up faulty CEL with datalog and alter OTF

# Protection measure notes
- MAP sensor max fluctuation
  - Detect failed/stuck sensor or hose that fell off
- MAT/CLT sensor max fluctuation: should be smooth in operation, used to detect a fault
- Battery max fluctuation: used to warn charging system faults or ground issues causing excessive voltage 'noise'
- EGO1 max fluctuation: detect a failed sensor, many wb controllers will get 'stuck' if the sensor fails although appearing to show a valid AFR reading. Combined with closed-loop or autotuning this can be troublesome without this detection scheme. Other controllers alllow an 'out of range' voltage output match the min/max ADC readings to capture this.
- No of sync losses allowed: during startup you may see 1 or 2 sync-losses, beyond that there is a problem with tach-in wiring or config
- EGT sensor max fluctuation: Temperatures are not check immediatly after startup so the min temp set to 200C to detect dead cylinder or faulty sensor. Max will depend on engine. NA may be 900 while boosted may be 1000C

# Limp mode
Limp mode protects the user from doing stupid thing when the engine is not up for the task anymore. Something is wrong and the car needs to be limped home as safe as possible.

This is why revs/boost are limited in limp mode.
Timing retard can be used as well but since we've yet to experience a limp condition on this ECU. We're going to leave that options as-is.

![image](https://user-images.githubusercontent.com/4503038/113481939-a93ba700-949c-11eb-8b92-b1cacea8d2b7.png)

## Todo

- [ ] Unhook MAP hose and wait for limp mode to engage to test
- [ ] Tune fallback MAP table

MAP can be derived from datalogs comparing MAP, RPM, TPS while driving

# Additional measures
## Todo

- [ ] Oil pressure sensor
- [ ] Enable AFR safety
- [ ] EGT sensor
- [ ] Flex fuel sensor
