### ISSUE TITLE
Exhaust and vacuum leaks

### ISSUE THREAD

**Issue by ackoujens** [ackoujens/tunerstudio-valor-740-super-turbo#9]
## Description
Exhaust leaks causes the wideband sensor to misread on the resulting fuel mixture.
Especially when leaks happen before this sensor, this needs to be rooted out and fixed.

Vacuum leaks are bad too as they are being read by the MAP sensor.
This signal not being accurate caused by leaks, you'll never be able to tell how much boost you're making.

Finding exhaust and vacuum leaks can be difficult. This is why a smoke tester can be handy in finding any.
A commercial version is really expensive but can also be made cheap from some basic items.

Example creation:
https://www.youtube.com/watch?v=tixozqgSwN0

- [ ] Make DIY smoke tester
- [ ] Fix Exhaust leaks
- [ ] Fix Vacuum leaks

If these items are addressed, further tuning and testing can go on.
Otherwise this would only be a wasted effort.

**Comment by ackoujens** [comment]
# Exhaust system repair

The exhaust system is not very well done and riddled with exhaust leaks.
A redo is in order and that is why we've ordered new O2 sensor bungs.
Either the current exhaust piping or from the parts car can be used, whichever is in better shape.

Rewelding the bungs and making sure everything is airtight without the use of exhaust repair paste.
Chances are, new exhaust gaskets are required for reinstallation.

Finishing this, exhaust system issues messing around with AFR values should be a problem of the past.

## Todo
- [x] Remove exhaust systems
- [x] Install new O2 bung
- [x] Test exhaust system before refitting
- [x] Install exhaust pipe, manifold, turbo

**Comment by ackoujens** [comment]
# Wideband installation procedure
_Bosch 02 sensor installation procedure._

## Installation Instructions
1. Remove protector cap just prior to installation
2. If not already coated, apply (enclosed) anti-seize to oxygen sensor threads.
3. Install sensor body ensuring lead wire is not twisted or bent
4. Install all sensors with new gasket supplied and torque to proper specs as below:
M18 sensors - Install finger tight then 1/2-3/4 turn with wrench / O2 sensor socket 26-33ft. lbs.
M12 sensors - Install finger tight then 3/4 - 1 turn with wrench / O2 sensor socket 13.2 -17ft. lbs.

A) Flanged applications - (where flange is NOT already installed on sensor) Install flange to exhaust manifold first, then mount sensor in flange (A copper gasket is bonded to the flange & no additional gasket is required)
B) Flanged applications - (where flange is already installed on sensor)
(it is important to use the supplied gasket before installing sensor)

5. Connect and route lead wire as originally installed
